spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: kelve
    password: 1234
  jpa:
    show-sql:  true
    #hibernate:
    propeties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html

